fix: only run taplo format if toml files are changed

diff --git a/.github/hooks/pre-commit b/.github/hooks/pre-commit
--- a/.github/hooks/pre-commit
+++ b/.github/hooks/pre-commit
@@ -13,13 +13,15 @@ if [ "$RESULT" != "0" ]; then
     exit $RESULT
 fi
 
-taplo format --check
-RESULT=$?
-if [ "$RESULT" != "0" ]; then
-    echo "INFO: pre-commit: taplo format failed"
-    echo "FAIL: pre-commit: aborting the commit"
-    exit $RESULT
+# Check if there are any .toml files that have changed
+if git diff --cached --name-only | grep -q '\.toml$'; then
+    taplo format --check
+    RESULT=$?
+    if [ "$RESULT" != "0" ]; then
+        echo "INFO: pre-commit: taplo format failed"
+        echo "FAIL: pre-commit: aborting the commit"
+        exit $RESULT
+    fi
 fi
-
 
 exit $RESULT
