Compare proofs once we have them

diff --git a/.github/workflows/check-prover.yml b/.github/workflows/check-prover.yml
--- a/.github/workflows/check-prover.yml
+++ b/.github/workflows/check-prover.yml
@@ -113,3 +113,119 @@ jobs:
           inputs: ${{ toJson(matrix) }}
           channel: "#noti-creditcoin-snapshots"
           message: "Checking CK(${{ matrix.chainKey }})@${{ matrix.proverUrl}} complete! cc <@U028EMRHS3S>"
+
+  compare-proofs-sepolia:
+    needs:
+      - check-for
+    runs-on: ubuntu-24.04
+    steps:
+      - name: Setup
+        run: |
+          sudo apt-get install colordiff unzip
+
+      - name: Download proofs from Sepolia CC3 Devnet
+        uses: actions/download-artifact@v8
+        with:
+          path: /var/tmp/proofs
+          pattern: proofs-for-cc3-devnet-ck-1
+
+      - name: Git commit proofs data
+        working-directory: /var/tmp/proofs
+        run: |
+          git config --global init.defaultBranch main
+          git config --global user.email "creditcoin@gluwa.com"
+          git config --global user.name "gluwa-bot"
+
+          git init
+          git add .
+          git commit -a -m "Import data"
+
+          # remove everything b/c next we'll download data from CC3 Testnet
+          rm -rf ./*
+
+      - name: Download proofs from Sepolia CC3 Testnet
+        uses: actions/download-artifact@v8
+        with:
+          path: /var/tmp/proofs
+          pattern: proofs-for-cc3-testnet-ck-1
+
+      - name: Compare
+        working-directory: /var/tmp/proofs
+        timeout-minutes: 5
+        run: |
+          git status
+
+          set -eo pipefail
+          # filter only modified content b/c between the 2 CI jobs we may not have
+          # proofs for exactly the same set of blocks
+          git diff --diff-filter=M | colordiff
+
+          # will exit non-zero in case of differences
+          git diff --quiet --diff-filter=M
+
+      - name: Report result to Slack
+        if: always()
+        uses: act10ns/slack@v2
+        with:
+          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
+          status: ${{ job.status }}
+          channel: "#noti-creditcoin-snapshots"
+          message: "Proofs diff for Sepolia complete! cc <@U028EMRHS3S>"
+
+  compare-proofs-ethereum:
+    needs:
+      - check-for
+    runs-on: ubuntu-24.04
+    steps:
+      - name: Setup
+        run: |
+          sudo apt-get install colordiff unzip
+
+      - name: Download proofs from Ethereum CC3 Devnet
+        uses: actions/download-artifact@v8
+        with:
+          path: /var/tmp/proofs
+          pattern: proofs-for-cc3-devnet-ck-4
+
+      - name: Git commit proofs data
+        working-directory: /var/tmp/proofs
+        run: |
+          git config --global init.defaultBranch main
+          git config --global user.email "creditcoin@gluwa.com"
+          git config --global user.name "gluwa-bot"
+
+          git init
+          git add .
+          git commit -a -m "Import data"
+
+          # remove everything b/c next we'll download data from CC3 Testnet
+          rm -rf ./*
+
+      - name: Download proofs from Ethereum CC3 Testnet
+        uses: actions/download-artifact@v8
+        with:
+          path: /var/tmp/proofs
+          pattern: proofs-for-cc3-testnet-ck-3
+
+      - name: Compare
+        working-directory: /var/tmp/proofs
+        timeout-minutes: 5
+        run: |
+          git status
+
+          set -eo pipefail
+          # filter only modified content b/c between the 2 CI jobs we may not have
+          # proofs for exactly the same set of blocks
+          git diff --diff-filter=M | colordiff
+
+          # will exit non-zero in case of differences
+          git diff --quiet --diff-filter=M
+
+      - name: Report result to Slack
+        if: always()
+        uses: act10ns/slack@v2
+        with:
+          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
+          status: ${{ job.status }}
+          channel: "#noti-creditcoin-snapshots"
+          message: "Proofs diff for Ethereum complete! cc <@U028EMRHS3S>"
