Execute benchmarks in CI & rebuild SUT with dummy weights

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -990,3 +990,78 @@ jobs:
         run: |
           echo "Skipped b/c of https://github.com/NomicFoundation/hardhat/discussions/5266"
           # npx hardhat node --fork https://rpc.cc3-testnet.creditcoin.network
+
+  benchmark:
+    needs:
+      # because of the shared cache
+      - build-creditcoin-node-for-testing
+    runs-on: ubuntu-24.04
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Inspect benchmark CI config
+        run: |
+          # WARNING: Command below may differ depending on which workflow config file
+          # your job is defined in !!! Don't copy&paste it blindly !!!
+          PALLETS_IN_CI_CONFIG=$(grep ".github/bench.sh -p" .github/workflows/ci.yml | grep -v PALLETS_IN_CI_CONFIG | tr -s ' ' | cut -d' ' -f4 | sort | xargs)
+
+          PALLETS_IN_SOURCE=$(.github/check-parity-bw-extrinsics-benchmarks-weights.sh --show-pallets)
+          if [ "$PALLETS_IN_CI_CONFIG" != "$PALLETS_IN_SOURCE" ]; then
+              echo "FAIL: Pallet mismatch between source code and benchmark CI config"
+              echo "INFO: in source: '$PALLETS_IN_SOURCE'"
+              echo "INFO: CI config: '$PALLETS_IN_CI_CONFIG'"
+              exit 1
+          fi
+
+      - name: Download creditcoin-node binary
+        uses: actions/download-artifact@v4
+        with:
+          name: creditcoin-node-for-testing-ci
+          path: target/release
+
+      - name: Check if runner machine meets chain's requirements
+        continue-on-error: true
+        run: |
+          chmod a+x ./target/release/creditcoin3-node
+          .github/check-hardware.sh
+
+      - name: Run benchmarks to generate dummy weights
+        run: |
+          .github/bench.sh -p attestation_poc -b -r 1 -s 2
+          .github/bench.sh -p prover -b -r 1 -s 2
+          .github/bench.sh -p supported_chains -b -r 1 -s 2
+
+      - name: Set-Up
+        run: |
+          sudo apt-get update
+          sudo apt install -y curl
+
+      - name: Install protobuf
+        uses: arduino/setup-protoc@v3
+        with:
+          repo-token: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Configure rustc version
+        run: |
+          RUSTC_VERSION=$(grep channel rust-toolchain.toml | tail -n1 | tr -d " " | cut -f2 -d'"')
+          echo "RUSTC_VERSION=$RUSTC_VERSION" >> "$GITHUB_ENV"
+
+      - name: Install Rust toolchain
+        uses: gluwa/toolchain@dev
+        with:
+          toolchain: ${{ env.RUSTC_VERSION }}
+          target: wasm32-unknown-unknown
+          profile: minimal
+          override: true
+
+      # use cache from previous build jobs
+      - uses: Swatinem/rust-cache@v2
+        with:
+          shared-key: build-creditcoin-node
+
+      # check if automatically generated weights compile
+      - name: Rebuild SUT with newly generated weights
+        uses: gluwa/cargo@dev
+        with:
+          command: build
+          args: --release
