Exercise scripts/SubmitProof.js in a CI job

diff --git a/.github/workflows/proof-gen-api-server.yml b/.github/workflows/proof-gen-api-server.yml
--- a/.github/workflows/proof-gen-api-server.yml
+++ b/.github/workflows/proof-gen-api-server.yml
@@ -193,6 +193,36 @@ jobs:
           .github/wait-for-creditcoin.sh 'http://127.0.0.1:9944'
           .github/wait-for-ethereum.sh 'http://127.0.0.1:8141'
 
+      - name: Install Node.js
+        uses: actions/setup-node@v6
+        with:
+          node-version: 20
+
+      - name: Simulate a native token transfer on Anvil 1
+        id: native-transfer-anvil-1
+        working-directory: attestor/scripts
+        run: |
+          npm install
+
+          OUTPUT=$(ETH_RPC_URL=http://127.0.0.1:8141 node Transfer.js)
+          echo "$OUTPUT"
+
+          BLOCK_NUMBER=$(echo "$OUTPUT" | grep block: | cut -f2 -d: | tr -d ' ')
+          TXN_HASH=$(echo "$OUTPUT" | grep hash: | cut -f2 -d: | tr -d ' ')
+
+          # Provide default values if extraction failed
+          if [ -z "$BLOCK_NUMBER" ]; then
+            echo "ERROR: Could not extract block number from Transfer.js output"
+            exit 1
+          fi
+          if [ -z "$TXN_HASH" ]; then
+            echo "ERROR: Could not extract transaction hash from Transfer.js output"
+            exit 2
+          fi
+
+          echo "block_number=$BLOCK_NUMBER" >> "$GITHUB_OUTPUT"
+          echo "txn_hash=$TXN_HASH" >> "$GITHUB_OUTPUT"
+
       - name: Start Attestation Zombienet
         run: |
           chmod a+x ./target/release/attestor*
@@ -231,11 +261,6 @@ jobs:
             >/var/tmp/exercise-TransferWaitAndSubmit-js/proof-gen-api-server.log &
 
           sleep 30
-
-      - name: Install Node.js
-        uses: actions/setup-node@v6
-        with:
-          node-version: 20
 
       - name: Exercise TransferWaitAndSubmit.js
         working-directory: scripts
@@ -286,6 +311,16 @@ jobs:
             --cc3-rpc-url ws://localhost:9944 \
             --cc3-private-key 0x5fb92d6e98884f76de468fa3f6278f8807c48bebc13595d45af5bdc4da702133 \
             --api-url http://localhost:3100
+
+      - name: Exercise SubmitProof.js
+        working-directory: scripts
+        run: |
+          # Using Alith on execution chain
+          node SubmitProof.js 2 ${{ steps.native-transfer-anvil-1.outputs.txn_hash }} \
+            --private-key 0x5fb92d6e98884f76de468fa3f6278f8807c48bebc13595d45af5bdc4da702133 \
+            --api-url http://localhost:3100 \
+            --cc3-rpc-url http://localhost:9944 \
+            --verbose
 
       - name: Upload logs
         if: always()
